### ISSUE TITLE
Perhaps build 17.1 from LineageOS-Revived instead?

### ISSUE THREAD

**Issue by the-r3dacted** [Flamefire/lineageos_lilac#6]
I think it would simplify the build process and patching as it has all the security patches.

Or maybe it has some patches you don't have, and those could be added to your repo if you'd rather keep the current method.

**Comment by Flamefire** [comment]
Interesting, I didn't know about https://github.com/LineageOS-Revived Thanks!

And yes I'd rather keep the current approach especially as I'm sure they use my patches anyway ;-) Their ASB patch is from 1 day after I uploaded my work to LOS gerrit and actually is equal to that. So I'd guess they "just" provide an easier way for others to use my work, which is great.

And:
> Also includes misc fixes and perfomance improvements from [crDroid](https://github.com/crdroidandroid), theme updates from [LightningFastRom](https://github.com/LightningFastRom) and signature spoofing support from [Mint OS](https://github.com/Mint-OS).

I'm rather wary of adding more changes in case it breaks something. But it makes sense to check their repos if I missed anything which could be useful. Adding signature spoofing to non-MicroG builds is something I'd oppose too.

**Comment by the-r3dacted** [comment]
> Adding signature spoofing to non-MicroG builds is something I'd oppose too.

I'm curious, wouldn't restricted style spoofing be fine? A simple edit restricts the signature spoofing patch (from LineageOS for MicroG) to system apps. I've made my own repo for building more than just Lilac, and included the patch. You can find the modified patch here.
https://github.com/Eclipse-Community/build_lineage/blob/lineage-17.1/patches/android_frameworks_base-Q.patch

To simplify stuff for myself I might just make a new repo that doesn't track Lilac device for patches, and just build revived.

Also, a bit unrelated to this, I'm curious about what it takes to maintain 17.1, 18.1, and 19.1 builds, and how much the device sources really differ between versions. Not entirely sure where to discuss this though.

**Comment by Flamefire** [comment]
> > Adding signature spoofing to non-MicroG builds is something I'd oppose too.
> 
> I'm curious, wouldn't restricted style spoofing be fine?

It isn't required outside MicroG and was never requested. That "feature" was denied multiple times by LineageOS maintainers for potentially weakening the security. So for MicroG I use the restricted spoofing patch and so can anyone else building from source. That's basically it: Don't mess with security if not really required.

> To simplify stuff for myself I might just make a new repo that doesn't track Lilac device for patches, and just build revived.

I guess that's their intention. So do that!

> Also, a bit unrelated to this, I'm curious about what it takes to maintain 17.1, 18.1, and 19.1 builds, and how much the device sources really differ between versions. Not entirely sure where to discuss this though.

It usually consists mainly of adding the security patches issued by Google each month and announced in the ASB. Google stopped issuing those for A10, so LOS stopped providing updates for 17.1. Hence I backported the Google patches from A11 to A10 manually. This often leads to conflicts when sources have changed to much from A10 to A11 which is quite some work and sometimes it just isn't possible or required. That needs investigation to decide. When Google stops A11 updates then backports would need to come from A12 causing even more potential for conflicts.    
At least I could previously pick each commit from the LOS ASB topic for 18.1 to 17.1 which is less work then picking them from Google directly due to them being nicely lined up already.   
So when Google stops ASB patches for A11 and LOS support for A12/19.1 it will be a lot more work to get all patches and apply them correctly.   
As for how sources differ: The largest changes in framework sources are added interfaces, changed method signatures or even porting Java classes to Kotlin. Try to track those changes back to earlier versions...

Hope that has answered your questions or at least gave you pointers where to search next. This issue here should be solved now, I believe

**Comment by the-r3dacted** [comment]
> As for how sources differ: The largest changes in framework sources are added interfaces, changed method signatures or even porting Java classes to Kotlin. Try to track those changes back to earlier versions...

I mean like device sources, kernel, and common. Say I wanted to take 17.1 sources and build 16.0 or 15.1, Or take 20 or 21 sources for XZ2C and build 17.1. How exactly would I go about doing this? Do I just try it and correct any issues as they come up? (I know 15.1 sources exist for XZ1C and 17.1 sources for XZ2C, but there are so many improvements in newer sources for these devices)

If it's better to cherry pick, how would I update the kernel for example? I notice you get your kernel commits from somewhere but I have no idea where.

**Comment by Flamefire** [comment]
> I mean like device sources, kernel, and common. Say I wanted to take 17.1 sources and build 16.0 or 15.1, Or take 20 or 21 sources for XZ2C and build 17.1. How exactly would I go about doing this? Do I just try it and correct any issues as they come up? 

Basically yes. Each Android versions has certain requirements about hardware services/interfaces and trying to get them working on the device is hard work requiring quite some research. Also the build system changes.   
So just try and then first fix the issues failing the build and then the issues showing up during boot or use. And you are pretty much on your own there as no one did that before for your device and that version (as otherwise you could just use that)

> If it's better to cherry pick, how would I update the kernel for example? I notice you get your kernel commits from somewhere but I have no idea where.

You can use the msm8998 common kernel from LOS as a start. But then you possibly need device specific modifications. Again you are on your own here.   
The cherry-picks I add are from CIP (merges from `*-st*`-tags) and those commits mentioned in the ASB.

**Comment by the-r3dacted** [comment]
> That "feature" was denied multiple times by LineageOS maintainers for potentially weakening the security

I spotted this actually, it looks like it just got merged into LineageOS officially (only 18.1 and up though)

https://review.lineageos.org/c/LineageOS/android_frameworks_base/+/383574

**Comment by the-r3dacted** [comment]
> So just try and then first fix the issues failing the build and then the issues showing up during boot or use. And you are pretty much on your own there as no one did that before for your device and that version (as otherwise you could just use that)

So I'm trying this with 19,1 sources and XZ2C to build 17.1. What is a runtime resource overlay and how do I make it recognized? Also what is system_ext_specific and how do I make it recognized?

**Comment by the-r3dacted** [comment]
Error messages that go hard
![DSC_0004](https://github.com/Flamefire/lineageos_lilac/assets/77039240/0f0b9c6a-173c-4e11-b100-a283c8d6fb0c)
